import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Climate Change Simmulation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`dark h-full antialiased bg-background-50 text-gray-300`}
    >
      <body className="min-h-full flex flex-col">
        <main className="w-full min-h-full p-12">
          {children}
        </main>
      </body>
    </html>
  );
}
